name: Feature Request
description: Suggest an idea or enhancement for the code-executor skill
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature relate to?
      options:
        - New Cached Script Pattern
        - New Template
        - MCP Client Enhancement
        - Documentation Improvement
        - Performance Optimization
        - Security Enhancement
        - Developer Experience
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: I also considered...

  - type: textarea
    id: examples
    attributes:
      label: Example Use Case
      description: Provide a concrete example of how this would be used
      placeholder: |
        User wants to...
        Subagent would...
        Result would be...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to contribute this feature
          required: false
